### ISSUE TITLE
CPGr I 14 incorrectly(?) joined with CPgr II 14

### ISSUE THREAD

**Issue by ryanfb** [papyri/navigator#70]
http://papyri.info/hgv/23022

As far as I can tell, these should be displayed separately.

**Comment by jcowey** [comment]
Should be fixed by:

https://github.com/papyri/idp.data/commit/f28ce36ae6f961030f25dbe7d20c1718b8a23016

Probably will not be correctly displayed until the next full re-index.

**Comment by jcowey** [comment]
http://papyri.info/hgv/23022
and (is the same as)
http://papyri.info/ddbdp/c.pap.gr;1;14
are now correct

**Comment by jcowey** [comment]
http://papyri.info/ddbdp/c.pap.gr;2.1;14/
still has old stuff
http://papyri.info/hgv/9243
does not work as it should.

These should be fine on a full re-index.

**Comment by jcowey** [comment]
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/c.pap.gr/c.pap.gr.2.1/c.pap.gr.2.1.14.xml#L14-L18
matches
https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV10/9243.xml#L10-L14

**Comment by hcayless** [comment]
@jcowey's fix to https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/bgu/bgu.2/bgu.2.583.xml got accidentally reverted a month later, which is why this is still broken. I've fixed it again, and will reindex next chance I get.

**Comment by ryanfb** [comment]
Seems (currently) fixed.
